
__version__ = '0.0.1'
# import india_compliance.gst_india.report.hsn_wise_summary_of_outward_supplies.hsn_wise_summary_of_outward_supplies
# import ambica_finance.hsn_wise_summary_of_outward_supplies
# india_compliance.gst_india.report.hsn_wise_summary_of_outward_supplies.hsn_wise_summary_of_outward_supplies.get_items = ambica_finance.hsn_wise_summary_of_outward_supplies.get_items
# india_compliance.gst_india.report.hsn_wise_summary_of_outward_supplies.hsn_wise_summary_of_outward_supplies.get_hsn_data = ambica_finance.hsn_wise_summary_of_outward_supplies.get_hsn_data

# import erpnext.accounts.general_ledger
# import ambica_finance.backend_code.general_ledger
# erpnext.accounts.general_ledger.make_gl_entries=ambica_finance.backend_code.general_ledger.make_gl_entries
# erpnext.accounts.general_ledger.save_entries=ambica_finance.backend_code.general_ledger.save_entries
# erpnext.accounts.general_ledger.make_entry=ambica_finance.backend_code.general_ledger.make_entry

